### ISSUE TITLE
iTunes doesn't work

### ISSUE THREAD

**Issue by kopytko95** [StigNygaard/Stigs_Art_Grabr#5]
Hello,

something must have been changed on itunes' side again, because script doesn't work there :(

Maybe it has something to do with the fact, it's  .webp instead of jpg now

**Comment by StigNygaard** [comment]
Those annoying developers at Apple. Can't they relax or work on something else? ;-)

> Maybe it has something to do with the fact, it's .webp instead of jpg now

Good catch. I think you are right. I'll take a look at it.

**Comment by kopytko95** [comment]
One thing - is it possible that downloaded image will still be JPG?

**Comment by StigNygaard** [comment]
It might take a little time before I get this fixed. But in the meantime I can remind about the sites fnd.io and musicdiner.com which both can be used to find music(covers) on Apple Music/iTunes. Art Grabr also supports those sites, and they mostly still seems to work.

**Comment by kopytko95** [comment]
Another question from me, would you mind adding this extension to chrome web store? I've recently (yesterday, to be exact) got new computer and chrome blocks me from adding extensions from outside the store, probably I'll be not the only one

**Comment by StigNygaard** [comment]
> chrome blocks me from adding extensions from outside the store

Hi @kopytko95 
And you have Tampermonkey or other userscript manager installed?
Can I find more information on the problem somewhere? I'm thinking/guessing it is probably something that could be solved by GreasyFork and/or Tampermonkey.

**Comment by kopytko95** [comment]
About that chrome store thing -> problem solved, there was pretty easy workaround that somehow i did not manage to find yesterday. Google does weird thinks with their browser to make sure we won't harm ourse;ves :|

**Comment by StigNygaard** [comment]
Hi @kopytko95 
iTunes should be working again  with the just released version 2020.12.28.0.
iTunes are serving both jpg and webp images depending on which page you are on. When webp, big version are currently also shown/downloaded as webp. But I see that, at least sometimes, replacing ".webp" with ".jpg" in filename will give you a jpg instead. I'm considering maybe making it an option somehow to choose jpg images instead of webp (Though i suspect Apple's plan is to phased out jpgs - so it might not work for long time).

**Comment by kopytko95** [comment]
.Webp for my purposes (rateyourmusic) is not supported (and if i simply change extension in the file from .webp to .jpg it still doesn't work)

I noticed one thing
https://is2-ssl.mzstatic.com/image/thumb/Music123/v4/16/43/4a/16434a01-fe42-4898-7427-2728736f0da8/053000811954_cover.jpg/999999x999999bb-100.webp ->
https://is2-ssl.mzstatic.com/image/thumb/Music123/v4/16/43/4a/16434a01-fe42-4898-7427-2728736f0da8/053000811954_cover.jpg/999999x999999bb-100.jpg

Image downloaded after changing the end of link to .jpg seems to be working for me. Is it possible to make it work this way? (Unless it's eventually better for you to keep .webp working as more future-proof solution for the script)

**Comment by StigNygaard** [comment]
> EDIT: Huh, i looked into your script and i did this adjustment by myself, it was easier than i expected; all images on iTunes are being"grabbd" as .jpg for me

He he. Yes, it's not so difficult to get working as long as iTunes always serves a jpg with same name/path except the file-extension 😊

**Comment by StigNygaard** [comment]
I have now updated script (version 2021.05.09.0) to automatically substitute .webp file-extensions with .jpg. And so in general for all supported sites in Art Grabr. 
This also "fixes" similar issue on Last.FM.
